### ISSUE TITLE
Restructure into several repositories

### ISSUE THREAD

**Issue by ju5t** [supportpal/supportpal-resources#11]
Let's say you want to start a new theme. You would have to:

- Copy templates/frontend/default into templates/frontend/your-theme
- Select the theme in SupportPal

Although this works there is a critical flaw. You can't keep track of changes in new releases with the help of git. You would have to go over the Supportpal commits, check what changed and copy it manually into your own theme. You're not taking full advantage of what git has to offer. 

The only way to get git to do its magic today is to:

- Clone this repository
- Create a new branch
- Make your changes in the default theme
- Merge the changes from Supportpal back in when there's a new release

The reason for this is because the assets folder includes static files for the frontend and backend. I don't understand why yet but it makes sense to include them in the actual template.

I would propose to change it to something like this:

```
|-- assets
|   |-- general
|   `-- installer
|-- lang (own repo)
|   `-- en
`-- templates
    |-- errors
    |-- frontend (own repo)
    |   `-- theme
    |       `-- assets
    `-- operator (own repo)
        `-- theme
            `-- assets
```

That way you can work on your theme in a similar way as this:
https://github.com/WHMCS/templates-six/#command-line-usage

Which makes Supportpal upgrade friendly.

**Comment by jshah4517** [comment]
We have decided to split out the components of this repository in to new repositories for 3.0.0:
- [Language Files](https://github.com/supportpal/language-files)
- [Frontend Template](https://github.com/supportpal/frontend-template)
- [Operator Panel Template](https://github.com/supportpal/operator-template)
- [Resources Assets](https://github.com/supportpal/resources-assets)
